name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0
  excel: ^4.0.6
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0
  pdf: ^3.11.3
  printing: ^5.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icono.png"
